FROM alpine:3.18.2 AS alpine
RUN apk update && apk add curl tar
WORKDIR /vscode
RUN curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tgz
RUN tar -xf ./vscode_cli.tgz
CMD ./code tunnel --no-sleep --accept-server-license-terms --name $(hostname)